# Generated by Django 5.2.8 on 2026-01-11 23:35

import datetime
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import taxis.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cuota_usd', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Legacy',
                'verbose_name_plural': 'Configuraciones Legacy',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_bcv', models.DecimalField(decimal_places=2, default=50.0, help_text='Tasa actual del BCV en Bolívares', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='legal/repositorio/', validators=[taxis.validators.validar_archivo_seguro])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('presidente', 'Presidente'), ('asociado', 'Asociado')], default='asociado', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[taxis.validators.validar_archivo_seguro])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)'), ('union', 'Unión estable de hecho')], max_length=20)),
                ('cedula_prefijo', models.CharField(choices=[('V', 'V'), ('E', 'E')], default='V', max_length=1)),
                ('cedula_identidad', models.CharField(max_length=10, unique=True)),
                ('cedula_archivo', models.FileField(blank=True, null=True, upload_to='documentos/cedulas/', validators=[taxis.validators.validar_archivo_seguro])),
                ('cedula_vencimiento', models.DateField(blank=True, null=True)),
                ('rif_prefijo', models.CharField(choices=[('V', 'V'), ('J', 'J'), ('E', 'E'), ('P', 'P'), ('G', 'G')], default='V', max_length=1)),
                ('rif', models.CharField(max_length=15, unique=True)),
                ('rif_archivo', models.FileField(blank=True, null=True, upload_to='documentos/rif/', validators=[taxis.validators.validar_archivo_seguro])),
                ('rif_vencimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[taxis.validators.validar_archivo_seguro])),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('monto_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('concepto', models.CharField(default='Cuota Mensual', max_length=100)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='taxis.conductor')),
            ],
            options={
                'unique_together': {('conductor', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('email_type', models.CharField(default='primary', max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('email', 'date', 'email_type')},
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('email_type', models.CharField(default='primary', max_length=30)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('last_resend_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('modulo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/', validators=[taxis.validators.validar_archivo_seguro])),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='taxis.deuda')),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='taxis.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Guárico', max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('calle_avenida', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('zona_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxis.municipio')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxis.parroquia')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='ubicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='taxis.ubicaciongeografica'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('anio', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('serial_niv', models.CharField(max_length=20, unique=True)),
                ('numero_casco', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], max_length=2, unique=True)),
                ('condicion', models.CharField(choices=[('operativo', 'Operativo'), ('inoperativo', 'Inoperativo')], default='operativo', max_length=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/', validators=[taxis.validators.validar_archivo_seguro])),
                ('patente_archivo', models.FileField(blank=True, null=True, upload_to='documentos/vehiculos/patente/', validators=[taxis.validators.validar_archivo_seguro])),
                ('patente_vencimiento', models.DateField(blank=True, null=True)),
                ('licencia_archivo', models.FileField(blank=True, null=True, upload_to='documentos/vehiculos/licencia/', validators=[taxis.validators.validar_archivo_seguro])),
                ('licencia_vencimiento', models.DateField(blank=True, null=True)),
                ('rcv_archivo', models.FileField(blank=True, null=True, upload_to='documentos/vehiculos/rcv/', validators=[taxis.validators.validar_archivo_seguro])),
                ('rcv_vencimiento', models.DateField(blank=True, null=True)),
                ('medico_archivo', models.FileField(blank=True, null=True, upload_to='documentos/vehiculos/medico/', validators=[taxis.validators.validar_archivo_seguro])),
                ('medico_vencimiento', models.DateField(blank=True, null=True)),
                ('circulacion_archivo', models.FileField(blank=True, null=True, upload_to='documentos/vehiculos/otros/', validators=[taxis.validators.validar_archivo_seguro])),
                ('registro_archivo', models.FileField(blank=True, null=True, upload_to='documentos/vehiculos/otros/', validators=[taxis.validators.validar_archivo_seguro])),
                ('bateria_amp', models.CharField(blank=True, max_length=15, null=True)),
                ('aceite_viscosidad', models.CharField(blank=True, max_length=15, null=True)),
                ('cauchos_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('aceite_ultimo_cambio', models.DateField(blank=True, null=True)),
                ('kit_tiempo_cambio', models.DateField(blank=True, null=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('capacidad', models.PositiveIntegerField(default=5)),
                ('tipo_unidad', models.CharField(default='Sedan', max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='taxis.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('result', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
