# Generated by Django 5.2.8 on 2026-01-12 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cedula_identidad',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='rif',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono_principal',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Tasa actual del BCV', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='documentolegal',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
