# Generated by Django 5.2.8 on 2026-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0002_customuser_phone_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='bateria_amp',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='bateria_amperaje',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Amperaje Batería'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible_litros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible_tipo',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Gasoil', 'Gasoil'), ('Gas', 'Gas GNV')], default='Gasolina', max_length=20),
        ),
    ]
