# Generated by Django 5.2.8 on 2025-12-02 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0002_customuser_email_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='presidente',
            field=models.ForeignKey(blank=True, help_text='Presidente al que pertenece este asociado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asociados', to=settings.AUTH_USER_MODEL),
        ),
    ]
