# Generated by Django 5.2.8 on 2025-12-02 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0003_customuser_presidente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_verification_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secondary_email_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secondary_email_verification_code',
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('email_type', models.CharField(choices=[('primary', 'Correo principal'), ('secondary', 'Correo secundario')], default='primary', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('last_resend_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('last_resend_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
