# Generated by Django 5.2.8 on 2026-01-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0003_remove_vehiculo_bateria_amp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='diametro_rin',
            field=models.CharField(default='14', max_length=5, verbose_name='Diámetro Rin'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='aceite_viscosidad',
            field=models.CharField(default='15W40', max_length=10, verbose_name='Viscosidad Aceite'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='bateria_amperaje',
            field=models.CharField(default='-', max_length=10, verbose_name='Amperaje Batería'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cauchos_medida',
            field=models.CharField(default='-', max_length=10, verbose_name='Medida Cauchos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible_litros',
            field=models.CharField(default='-', max_length=10, verbose_name='Litros Tanque'),
            preserve_default=False,
        ),
    ]
