# Generated by Django 5.2.8 on 2025-12-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0004_remove_customuser_email_code_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email_primary', 'Email principal'), ('email_secondary', 'Email secundario'), ('sms', 'SMS')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('result', models.CharField(choices=[('success', 'Éxito'), ('invalid_code', 'Código inválido'), ('expired', 'Código expirado'), ('too_many_attempts', 'Demasiados intentos'), ('resend_blocked', 'Reenvío bloqueado')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
