# Generated by Django 5.2.8 on 2026-01-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0004_vehiculo_diametro_rin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['numero_casco', 'placa']},
        ),
    ]
