# Generated by Django 5.0 on 2026-01-20 20:38

import django.db.models.deletion
import django.utils.timezone
import taxis.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0005_alter_conductor_options_alter_vehiculo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cuota_usd', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('dia_vencimiento', models.IntegerField(default=5)),
                ('descripcion', models.CharField(default='Cuota mensual cooperativa', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Finanzas',
                'verbose_name_plural': 'Configuraciones de Finanzas',
            },
        ),
        migrations.CreateModel(
            name='PagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/pagos/', validators=[taxis.validators.validar_archivo_seguro])),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_mensuales', to='taxis.conductor')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxis.vehiculo')),
            ],
            options={
                'verbose_name': 'Pago Mensual',
                'verbose_name_plural': 'Pagos Mensuales',
                'ordering': ['-anio', '-mes', '-fecha_pago'],
                'indexes': [models.Index(fields=['anio', 'mes'], name='taxis_pagom_anio_6ed879_idx'), models.Index(fields=['conductor', 'anio'], name='taxis_pagom_conduct_347c73_idx')],
                'unique_together': {('conductor', 'mes', 'anio')},
            },
        ),
    ]
