# Generated by Django 5.2.8 on 2025-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0005_verificationattemptlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_secondary_email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secondary_email',
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email_type',
            field=models.CharField(choices=[('primary', 'Correo principal')], default='primary', max_length=10),
        ),
        migrations.AlterField(
            model_name='verificationattemptlog',
            name='method',
            field=models.CharField(choices=[('email_primary', 'Email principal'), ('sms', 'SMS')], max_length=20),
        ),
    ]
