# Generated by Django 5.2.8 on 2025-12-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0006_remove_customuser_is_secondary_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='presidente',
        ),
    ]
