# Generated by Django 5.2.8 on 2026-01-21 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0006_configuracionfinanzas_pagomensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomensual',
            name='conductor_cedula_cache',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagomensual',
            name='conductor_nombre_cache',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_mensuales', to='taxis.conductor'),
        ),
    ]
