# Generated by Django 5.2.8 on 2025-12-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0007_remove_customuser_presidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email_type',
            field=models.CharField(choices=[('primary', 'Correo principal')], default='primary', max_length=30),
        ),
    ]
