# Generated by Django 5.2.8 on 2026-01-21 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0007_pagomensual_conductor_cedula_cache_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pagomensual',
            name='taxis_pagom_anio_6ed879_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagomensual',
            name='taxis_pagom_conduct_347c73_idx',
        ),
        migrations.AddField(
            model_name='pagomensual',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Pagos archivados (mayores a 5 años)'),
        ),
        migrations.AddField(
            model_name='pagomensual',
            name='fecha_archivado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se archivó el registro', null=True),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='anio',
            field=models.PositiveIntegerField(help_text='Año del pago', validators=[django.core.validators.MinValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Captura de pago móvil, transferencia, etc.', null=True, upload_to='comprobantes/pagos/'),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='conductor',
            field=models.ForeignKey(help_text='Afiliado que realizó el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_mensuales', to='taxis.conductor'),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='conductor_cedula_cache',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='conductor_nombre_cache',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='fecha_pago',
            field=models.DateField(help_text='Fecha en que se realizó el pago'),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='mes',
            field=models.PositiveSmallIntegerField(help_text='Mes del pago (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='monto_usd',
            field=models.DecimalField(decimal_places=2, help_text='Monto en dólares (USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones adicionales'),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagomensual',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='Vehículo asociado al pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_vehiculo', to='taxis.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='pagomensual',
            index=models.Index(fields=['archivado', 'anio', 'mes'], name='taxis_pagom_archiva_1f261c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagomensual',
            index=models.Index(fields=['conductor', 'archivado'], name='taxis_pagom_conduct_ab6887_idx'),
        ),
        migrations.AddIndex(
            model_name='pagomensual',
            index=models.Index(fields=['fecha_pago'], name='taxis_pagom_fecha_p_0df445_idx'),
        ),
    ]
