# Generated by Django 5.2.8 on 2025-12-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0008_alter_emailverificationcode_email_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('email', 'date')},
            },
        ),
    ]
