# Generated by Django 5.2.8 on 2026-01-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0008_remove_pagomensual_taxis_pagom_anio_6ed879_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
