# Generated by Django 5.2.8 on 2025-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0009_emailsendlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationattemptlog',
            name='method',
            field=models.CharField(choices=[('email_primary', 'Email principal')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PhoneVerificationCode',
        ),
    ]
