# Generated by Django 5.2.8 on 2026-01-22 03:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0009_delete_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoaudit',
            name='cambios_antes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='movimientoaudit',
            name='cambios_despues',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='movimientoaudit',
            name='descripcion',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoaudit',
            name='fecha_formato',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimientoaudit',
            name='objeto_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoaudit',
            name='objeto_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movimientoaudit',
            name='objeto_tipo',
            field=models.CharField(default='--', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientoaudit',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver Detalle'), ('listar', 'Listar'), ('pago_registrado', 'Registrar Pago'), ('masivo', 'Acción Masiva'), ('configurar', 'Configuración'), ('exportar', 'Exportar Reporte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoaudit',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientoaudit',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movimientoaudit',
            index=models.Index(fields=['usuario', '-fecha'], name='taxis_movim_usuario_4a34ae_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoaudit',
            index=models.Index(fields=['modulo', '-fecha'], name='taxis_movim_modulo_5ff018_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoaudit',
            index=models.Index(fields=['accion'], name='taxis_movim_accion_b35732_idx'),
        ),
    ]
