# Generated by Django 5.2.8 on 2026-01-24 01:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0010_movimientoaudit_cambios_antes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPresidentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_country', models.CharField(blank=True, default='', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email',), name='uniq_pending_pres_email'), models.UniqueConstraint(fields=('phone_number',), name='uniq_pending_pres_phone')],
            },
        ),
    ]
