# Generated by Django 5.2.8 on 2025-12-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0010_alter_verificationattemptlog_method_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailsendlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailsendlog',
            name='email_type',
            field=models.CharField(choices=[('primary', 'Correo principal / registro'), ('password_reset', 'Restablecimiento de contraseña')], default='primary', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='emailsendlog',
            unique_together={('email', 'date', 'email_type')},
        ),
    ]
