# Generated by Django 5.2.8 on 2026-01-04 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0011_alter_emailsendlog_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ubicaciongeografica',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='ubicaciongeografica',
            name='nro_casa',
        ),
        migrations.AddField(
            model_name='conductor',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)'), ('union', 'Unión estable de hecho')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono_principal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono_secundario',
            field=models.CharField(blank=True, help_text='Opcional.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario asociado al perfil de conductor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ubicaciongeografica',
            name='calle_avenida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ubicaciongeografica',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ubicaciongeografica',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ubicaciongeografica',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ubicaciongeografica',
            name='zona_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='ubicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='taxis.ubicaciongeografica'),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
