# Generated by Django 5.2.8 on 2026-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0011_pendingpresidentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se envió el correo de activación por PRIMERA VEZ', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_locked_until',
            field=models.DateTimeField(blank=True, help_text='Bloqueado hasta esta fecha (30 min si se agotan intentos)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_resend_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de reenvíos de correo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_resend_last_at',
            field=models.DateTimeField(blank=True, help_text='Fecha del último reenvío', null=True),
        ),
    ]
