# Generated by Django 5.2.8 on 2026-01-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0012_customuser_activation_email_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_email_sent_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_locked_until',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_resend_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_resend_last_at',
        ),
    ]
