# Generated by Django 5.2.8 on 2026-01-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0012_rename_apellido_conductor_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del asociado.', null=True, upload_to='avatars/'),
        ),
    ]
