# Generated by Django 5.2.8 on 2026-01-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0013_remove_customuser_activation_email_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parroquia',
            name='municipio',
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='municipio',
            field=models.CharField(blank=True, choices=[('Juan Germán Roscio', 'Juan Germán Roscio'), ('Francisco de Miranda', 'Francisco de Miranda'), ('Leonardo Infante', 'Leonardo Infante'), ('José Tadeo Monagas', 'José Tadeo Monagas'), ('Julián Mellado', 'Julián Mellado'), ('Ortiz', 'Ortiz'), ('San Gerónimo de Guayabal', 'San Gerónimo de Guayabal'), ('Juan José Rondón', 'Juan José Rondón'), ('Pedro Zaraza', 'Pedro Zaraza'), ('José Félix Ribas', 'José Félix Ribas'), ('Santa María de Ipire', 'Santa María de Ipire'), ('Camaguán', 'Camaguán'), ('El Socorro', 'El Socorro'), ('Chaguaramas', 'Chaguaramas'), ('San José de Guaribe', 'San José de Guaribe')], help_text='Municipio del estado Guárico', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='parroquia',
            field=models.CharField(blank=True, choices=[('San Juan de los Morros (Capital)', 'San Juan de los Morros (Capital)'), ('Parapara', 'Parapara'), ('Cantagallo', 'Cantagallo'), ('Capital Urbana Calabozo', 'Capital Urbana Calabozo'), ('El Calvario', 'El Calvario'), ('El Rastro', 'El Rastro'), ('Guardatinajas', 'Guardatinajas'), ('Valle de la Pascua (Capital)', 'Valle de la Pascua (Capital)'), ('Espino', 'Espino'), ('Altagracia de Orituco (Capital)', 'Altagracia de Orituco (Capital)'), ('San Rafael de Orituco', 'San Rafael de Orituco'), ('San Francisco Javier de Lezama', 'San Francisco Javier de Lezama'), ('Paso Real de Macaira', 'Paso Real de Macaira'), ('Carlos Soublette', 'Carlos Soublette'), ('San Francisco de Macaira', 'San Francisco de Macaira'), ('Libertad de Orituco', 'Libertad de Orituco'), ('El Sombrero (Capital)', 'El Sombrero (Capital)'), ('Sosa', 'Sosa'), ('Ortiz (Capital)', 'Ortiz (Capital)'), ('San Francisco de Tiznados', 'San Francisco de Tiznados'), ('San José de Tiznados', 'San José de Tiznados'), ('San Lorenzo de Tiznados', 'San Lorenzo de Tiznados'), ('Guayabal (Capital)', 'Guayabal (Capital)'), ('Cazorla', 'Cazorla'), ('Las Mercedes del Llano (Capital)', 'Las Mercedes del Llano (Capital)'), ('Cabruta', 'Cabruta'), ('Santa Rita de Manapire', 'Santa Rita de Manapire'), ('Zaraza (Capital)', 'Zaraza (Capital)'), ('San José de Unare', 'San José de Unare'), ('Tucupido (Capital)', 'Tucupido (Capital)'), ('San Rafael de Laya', 'San Rafael de Laya'), ('Santa María de Ipire (Capital)', 'Santa María de Ipire (Capital)'), ('Altamira', 'Altamira'), ('Camaguán (Capital)', 'Camaguán (Capital)'), ('Puerto Miranda', 'Puerto Miranda'), ('Uverito', 'Uverito'), ('El Socorro (Capital)', 'El Socorro (Capital)'), ('Chaguaramas (Capital)', 'Chaguaramas (Capital)'), ('San José de Guaribe (Capital)', 'San José de Guaribe (Capital)')], help_text='Parroquia del municipio seleccionado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='zona_postal',
            field=models.CharField(blank=True, choices=[('2301', '2301 - San Juan de los Morros / Cantagallo'), ('2302', '2302 - Ortiz'), ('2303', '2303 - Parapara'), ('2304', '2304 - San Francisco de Tiznados / San Lorenzo de Tiznados'), ('2305', '2305 - San José de Tiznados'), ('2306', '2306 - San Rafael de Laya'), ('2311', '2311 - Espino'), ('2312', '2312 - Calabozo'), ('2313', '2313 - Camaguán / Puerto Miranda / Uverito'), ('2314', '2314 - El Calvario'), ('2315', '2315 - El Rastro'), ('2316', '2316 - Guardatinajas'), ('2317', '2317 - Guayabal'), ('2319', '2319 - El Sombrero / Sosa'), ('2320', '2320 - Altagracia de Orituco'), ('2322', '2322 - San Rafael de Orituco'), ('2323', '2323 - San José de Guaribe'), ('2324', '2324 - San Francisco de Macaira'), ('2327', '2327 - Cazorla'), ('2328', '2328 - Paso Real de Macaira'), ('2330', '2330 - Tucupido'), ('2332', '2332 - Zaraza / San José de Unare'), ('2350', '2350 - Valle de la Pascua'), ('2354', '2354 - Santa María de Ipire / Altamira'), ('2355', '2355 - El Socorro'), ('2356', '2356 - Las Mercedes del Llano / Cabruta / Santa Rita de Manapire'), ('2358', '2358 - Chaguaramas')], help_text='Código postal de la localidad', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Parroquia',
        ),
    ]
