# Generated by Django 5.2.8 on 2026-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0014_customuser_fecha_nacimiento_customuser_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='telefono_fijo',
            field=models.CharField(blank=True, help_text='Opcional.', max_length=20, null=True),
        ),
    ]
