# Generated by Django 5.2.8 on 2026-01-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0014_remove_parroquia_municipio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='estado_civil',
            new_name='estadocivil',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='fecha_nacimiento',
            new_name='fechanacimiento',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('presidente', 'Presidente')], default='asociado', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='municipio',
            field=models.CharField(blank=True, help_text='Municipio del estado Guárico', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='parroquia',
            field=models.CharField(blank=True, help_text='Parroquia del municipio seleccionado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='zona_postal',
            field=models.CharField(blank=True, help_text='Código postal de la localidad', max_length=10, null=True),
        ),
    ]
