# Generated by Django 5.2.8 on 2026-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0015_rename_estado_civil_conductor_estadocivil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cedula_identidad',
            field=models.CharField(blank=True, help_text='Cédula única para presidentes', max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rif',
            field=models.CharField(blank=True, help_text='RIF único para presidentes', max_length=12, null=True, unique=True),
        ),
    ]
