# Generated by Django 5.2.8 on 2026-01-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0015_conductor_telefono_fijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='cedula_identidad',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
