# Generated by Django 5.2.8 on 2026-01-25 18:19

import taxis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0016_customuser_cedula_identidad_customuser_rif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='cedula_archivo',
        ),
        migrations.AddField(
            model_name='conductor',
            name='cedula_archivo_frente',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cedulas/', validators=[taxis.validators.validar_archivo_seguro], verbose_name='Cédula - Frente'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='cedula_archivo_reverso',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cedulas/', validators=[taxis.validators.validar_archivo_seguro], verbose_name='Cédula - Reverso'),
        ),
    ]
