# Generated by Django 5.2.8 on 2026-01-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0016_alter_conductor_cedula_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='documento_rif',
            field=models.FileField(blank=True, help_text='Archivo PDF o imagen escaneada del RIF vigente.', null=True, upload_to='documentos/rif/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_rif',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del RIF.', null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='rif',
            field=models.CharField(blank=True, help_text='Número de RIF tal cual aparece en el documento (Ej: V-12345678-0).', max_length=20, null=True),
        ),
    ]
