# Generated by Django 5.2.8 on 2026-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0017_remove_conductor_cedula_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicaciongeografica',
            name='sector',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
