# Generated by Django 5.2.8 on 2026-01-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0017_conductor_documento_rif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciongeografica',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
