# Generated by Django 5.2.8 on 2026-01-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0018_ubicaciongeografica_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario.', null=True, upload_to='avatars/'),
        ),
    ]
