# Generated by Django 5.2.8 on 2026-01-25 23:08

import taxis.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0018_alter_conductor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(upload_to='vehiculos/', validators=[taxis.validators.validar_archivo_seguro]),
        ),
    ]
