# Generated by Django 5.2.8 on 2026-01-28 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0019_alter_vehiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='cedula_identidad',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='rif',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
    ]
