# Generated by Django 5.2.8 on 2026-01-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0020_alter_conductor_cedula_identidad_alter_conductor_rif'),
    ]

    operations = [
    ]
