# Generated by Django 5.2.8 on 2026-01-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0021_add_conductor_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='aceite_viscosidad',
            field=models.CharField(max_length=10, verbose_name='Viscosidad Aceite'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='diametro_rin',
            field=models.CharField(max_length=5, verbose_name='Diámetro Rin'),
        ),
    ]
