# Generated by Django 4.2.27 on 2026-02-04 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0022_alter_vehiculo_aceite_viscosidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativaLegalDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_constitutiva_estatutos', models.FileField(blank=True, null=True, upload_to='cooperativa/legal/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('acta_asamblea_extraordinaria', models.FileField(blank=True, null=True, upload_to='cooperativa/legal/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coop_legal_docs_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
