# Generated by Django 4.2.27 on 2026-02-04 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taxis.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0023_cooperativalegaldocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidenteIdentificacionDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_frente', models.FileField(blank=True, null=True, upload_to=taxis.models.upload_presidente_docs)),
                ('cedula_detras', models.FileField(blank=True, null=True, upload_to=taxis.models.upload_presidente_docs)),
                ('rif', models.FileField(blank=True, null=True, upload_to=taxis.models.upload_presidente_docs)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ident_docs_updates', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ident_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
