# Generated by Django 4.2.27 on 2026-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0024_presidenteidentificaciondocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoaudit',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver Detalle'), ('listar', 'Listar'), ('pago_registrado', 'Registrar Pago'), ('masivo', 'Acción Masiva'), ('configurar', 'Configuración'), ('exportar', 'Exportar Reporte')], max_length=255),
        ),
    ]
