# Generated by Django 4.2.27 on 2026-02-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0025_alter_movimientoaudit_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagomensual',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Afiliado que realizó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_mensuales', to='taxis.conductor'),
        ),
    ]
