# Generated by Django 4.2.27 on 2026-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0026_alter_pagomensual_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoaudit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoaudit',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
